/**
 * @class Base
 * @singleton
 * @author Tayfun Öziş ERİKAN <tayfun.ozis.erikan@lab2023.com>
 *
 * Kebab Kernel Base class and requirements
 */
Ext.define('Kebab.kernel.Base', {
    singleton: true,
    extend: 'Ext.util.Observable',

    requires: [
        'Kebab.kernel.override.Window',
        'Kebab.kernel.app.Application',
        'Kebab.kernel.EventBusManager',
        'Kebab.kernel.component.Launcher',
        'Ext.ux.window.Notification'
    ],

    constructor: function() {
        var me = this;

        me._initUtils();
    },

    _initUtils: function() {

        // add ucFirst
        String.prototype.ucFirst = function() {
            return this.charAt(0).toUpperCase() + this.substr(1);
        }

        // add lcFirst
        String.prototype.lcFirst = function() {
            return this.charAt(0).toLowerCase() + this.substr(1);
        }
    },

    timeZonesData: [
        { value:"Casablanca",   name:"(GMT+00:00) Casablanca" },
        { value:"Dublin", name:"(GMT+00:00) Dublin" },
        { value:"Edinburgh", name:"(GMT+00:00) Edinburgh" },
        { value:"Lisbon", name:"(GMT+00:00) Lisbon" },
        { value:"London", name:"(GMT+00:00) London" },
        { value:"Monrovia", name:"(GMT+00:00) Monrovia" },
        { value:"UTC", name:"(GMT+00:00) UTC" },
        { value:"Amsterdam", name:"(GMT+01:00) Amsterdam" },
        { value:"Belgrade", name:"(GMT+01:00) Belgrade" },
        { value:"Berlin", name:"(GMT+01:00) Berlin" },
        { value:"Bern", name:"(GMT+01:00) Bern" },
        { value:"Bratislava", name:"(GMT+01:00) Bratislava" },
        { value:"Brussels", name:"(GMT+01:00) Brussels" },
        { value:"Budapest", name:"(GMT+01:00) Budapest" },
        { value:"Copenhagen", name:"(GMT+01:00) Copenhagen" },
        { value:"Ljubljana", name:"(GMT+01:00) Ljubljana" },
        { value:"Madrid", name:"(GMT+01:00) Madrid" },
        { value:"Paris", name:"(GMT+01:00) Paris" },
        { value:"Prague", name:"(GMT+01:00) Prague" },
        { value:"Rome", name:"(GMT+01:00) Rome" },
        { value:"Sarajevo", name:"(GMT+01:00) Sarajevo" },
        { value:"Skopje", name:"(GMT+01:00) Skopje" },
        { value:"Stockholm", name:"(GMT+01:00) Stockholm" },
        { value:"Vienna", name:"(GMT+01:00) Vienna" },
        { value:"Warsaw", name:"(GMT+01:00) Warsaw" },
        { value:"West Central Africa", name:"(GMT+01:00) West Central Africa" },
        { value:"Zagreb", name:"(GMT+01:00) Zagreb" },
        { value:"Athens", name:"(GMT+02:00) Athens" },
        { value:"Bucharest", name:"(GMT+02:00) Bucharest" },
        { value:"Cairo", name:"(GMT+02:00) Cairo" },
        { value:"Harare", name:"(GMT+02:00) Harare" },
        { value:"Helsinki", name:"(GMT+02:00) Helsinki" },
        { value:"Istanbul", name:"(GMT+02:00) Istanbul" },
        { value:"Jerusalem", name:"(GMT+02:00) Jerusalem" },
        { value:"Kyev", name:"(GMT+02:00) Kyev" },
        { value:"Minsk", name:"(GMT+02:00) Minsk" },
        { value:"Pretoria", name:"(GMT+02:00) Pretoria" },
        { value:"Riga", name:"(GMT+02:00) Riga" },
        { value:"Sofia", name:"(GMT+02:00) Sofia" },
        { value:"Tallinn", name:"(GMT+02:00) Tallinn" },
        { value:"Vilnius", name:"(GMT+02:00) Vilnius" },
        { value:"Baghdad", name:"(GMT+03:00) Baghdad" },
        { value:"Kuwait", name:"(GMT+03:00) Kuwait" },
        { value:"Moscow", name:"(GMT+03:00) Moscow" },
        { value:"Nairobi", name:"(GMT+03:00) Nairobi" },
        { value:"Riyadh", name:"(GMT+03:00) Riyadh" },
        { value:"St. Petersburg", name:"(GMT+03:00) St. Petersburg" },
        { value:"Volgograd", name:"(GMT+03:00) Volgograd" },
        { value:"Tehran", name:"(GMT+03:30) Tehran" },
        { value:"Abu Dhabi", name:"(GMT+04:00) Abu Dhabi" },
        { value:"Baku", name:"(GMT+04:00) Baku" },
        { value:"Muscat", name:"(GMT+04:00) Muscat" },
        { value:"Tbilisi", name:"(GMT+04:00) Tbilisi" },
        { value:"Yerevan", name:"(GMT+04:00) Yerevan" },
        { value:"Kabul", name:"(GMT+04:30) Kabul" },
        { value:"Ekaterinburg", name:"(GMT+05:00) Ekaterinburg" },
        { value:"Islamabad", name:"(GMT+05:00) Islamabad" },
        { value:"Karachi", name:"(GMT+05:00) Karachi" },
        { value:"Tashkent", name:"(GMT+05:00) Tashkent" },
        { value:"Chennai", name:"(GMT+05:30) Chennai" },
        { value:"Kolkata", name:"(GMT+05:30) Kolkata" },
        { value:"Mumbai", name:"(GMT+05:30) Mumbai" },
        { value:"New Delhi", name:"(GMT+05:30) New Delhi" },
        { value:"Sri Jayawardenepura", name:"(GMT+05:30) Sri Jayawardenepura" },
        { value:"Kathmandu", name:"(GMT+05:45) Kathmandu" },
        { value:"Almaty", name:"(GMT+06:00) Almaty" },
        { value:"Astana", name:"(GMT+06:00) Astana" },
        { value:"Dhaka", name:"(GMT+06:00) Dhaka" },
        { value:"Novosibirsk", name:"(GMT+06:00) Novosibirsk" },
        { value:"Rangoon", name:"(GMT+06:30) Rangoon" },
        { value:"Bangkok", name:"(GMT+07:00) Bangkok" },
        { value:"Hanoi", name:"(GMT+07:00) Hanoi" },
        { value:"Jakarta", name:"(GMT+07:00) Jakarta" },
        { value:"Krasnoyarsk", name:"(GMT+07:00) Krasnoyarsk" },
        { value:"Beijing", name:"(GMT+08:00) Beijing" },
        { value:"Chongqing", name:"(GMT+08:00) Chongqing" },
        { value:"Hong Kong", name:"(GMT+08:00) Hong Kong" },
        { value:"Irkutsk", name:"(GMT+08:00) Irkutsk" },
        { value:"Kuala Lumpur", name:"(GMT+08:00) Kuala Lumpur" },
        { value:"Perth", name:"(GMT+08:00) Perth" },
        { value:"Singapore", name:"(GMT+08:00) Singapore" },
        { value:"Taipei", name:"(GMT+08:00) Taipei" },
        { value:"Ulaan Bataar", name:"(GMT+08:00) Ulaan Bataar" },
        { value:"Urumqi", name:"(GMT+08:00) Urumqi" },
        { value:"Osaka", name:"(GMT+09:00) Osaka" },
        { value:"Sapporo", name:"(GMT+09:00) Sapporo" },
        { value:"Seoul", name:"(GMT+09:00) Seoul" },
        { value:"Tokyo", name:"(GMT+09:00) Tokyo" },
        { value:"Yakutsk", name:"(GMT+09:00) Yakutsk" },
        { value:"Adelaide", name:"(GMT+09:30) Adelaide" },
        { value:"Darwin", name:"(GMT+09:30) Darwin" },
        { value:"Brisbane", name:"(GMT+10:00) Brisbane" },
        { value:"Canberra", name:"(GMT+10:00) Canberra" },
        { value:"Guam", name:"(GMT+10:00) Guam" },
        { value:"Hobart", name:"(GMT+10:00) Hobart" },
        { value:"Melbourne", name:"(GMT+10:00) Melbourne" },
        { value:"Port Moresby", name:"(GMT+10:00) Port Moresby" },
        { value:"Sydney", name:"(GMT+10:00) Sydney" },
        { value:"Vladivostok", name:"(GMT+10:00) Vladivostok" },
        { value:"Magadan", name:"(GMT+11:00) Magadan" },
        { value:"New Caledonia", name:"(GMT+11:00) New Caledonia" },
        { value:"Solomon Is.", name:"(GMT+11:00) Solomon Is." },
        { value:"Auckland", name:"(GMT+12:00) Auckland" },
        { value:"Fiji", name:"(GMT+12:00) Fiji" },
        { value:"Kamchatka", name:"(GMT+12:00) Kamchatka" },
        { value:"Marshall Is.", name:"(GMT+12:00) Marshall Is." },
        { value:"Wellington", name:"(GMT+12:00) Wellington" },
        { value:"Nuku'alofa", name:"(GMT+13:00) Nuku'alofa" },
        { value:"Hawaii", name:"(GMT-10:00) Hawaii" },
        { value:"Alaska", name:"(GMT-09:00) Alaska" },
        { value:"Pacific Time (US & Canada)", name:"(GMT-08:00) Pacific Time (US & Canada)" },
        { value:"Arizona", name:"(GMT-07:00) Arizona" },
        { value:"Mountain Time (US & Canada)", name:"(GMT-07:00) Mountain Time (US & Canada)" },
        { value:"Central Time (US & Canada)", name:"(GMT-06:00) Central Time (US & Canada)" },
        { value:"Eastern Time (US & Canada)", name:"(GMT-05:00) Eastern Time (US & Canada)" },
        { value:"Indiana (East)", name:"(GMT-05:00) Indiana (East)" },
        { value:"International Date Line West", name:"(GMT-11:00) International Date Line West" },
        { value:"Midway Island", name:"(GMT-11:00) Midway Island" },
        { value:"Samoa", name:"(GMT-11:00) Samoa" },
        { value:"Hawaii", name:"(GMT-10:00) Hawaii" },
        { value:"Alaska", name:"(GMT-09:00) Alaska" },
        { value:"Pacific Time (US & Canada)", name:"(GMT-08:00) Pacific Time (US & Canada)" },
        { value:"Tijuana", name:"(GMT-08:00) Tijuana" },
        { value:"Arizona", name:"(GMT-07:00) Arizona" },
        { value:"Chihuahua", name:"(GMT-07:00) Chihuahua" },
        { value:"Mazatlan", name:"(GMT-07:00) Mazatlan" },
        { value:"Mountain Time (US & Canada)", name:"(GMT-07:00) Mountain Time (US & Canada)" },
        { value:"Central America", name:"(GMT-06:00) Central America" },
        { value:"Central Time (US & Canada)", name:"(GMT-06:00) Central Time (US & Canada)" },
        { value:"Guadalajara", name:"(GMT-06:00) Guadalajara" },
        { value:"Mexico City", name:"(GMT-06:00) Mexico City" },
        { value:"Monterrey", name:"(GMT-06:00) Monterrey" },
        { value:"Saskatchewan", name:"(GMT-06:00) Saskatchewan" },
        { value:"Bogota", name:"(GMT-05:00) Bogota" },
        { value:"Eastern Time (US & Canada)", name:"(GMT-05:00) Eastern Time (US & Canada)" },
        { value:"Indiana (East)", name:"(GMT-05:00) Indiana (East)" },
        { value:"Lima", name:"(GMT-05:00) Lima" },
        { value:"Quito", name:"(GMT-05:00) Quito" },
        { value:"Caracas", name:"(GMT-04:30) Caracas" },
        { value:"Atlantic Time (Canada)", name:"(GMT-04:00) Atlantic Time (Canada)" },
        { value:"La Paz", name:"(GMT-04:00) La Paz" },
        { value:"Santiago", name:"(GMT-04:00) Santiago" },
        { value:"Newfoundland", name:"(GMT-03:30) Newfoundland" },
        { value:"Brasilia", name:"(GMT-03:00) Brasilia" },
        { value:"Buenos Aires", name:"(GMT-03:00) Buenos Aires" },
        { value:"Georgetown", name:"(GMT-03:00) Georgetown" },
        { value:"Greenland", name:"(GMT-03:00) Greenland" },
        { value:"Mid-Atlantic", name:"(GMT-02:00) Mid-Atlantic" },
        { value:"Azores", name:"(GMT-01:00) Azores" },
        { value:"Cape Verde Is.", name:"(GMT-01:00) Cape Verde Is." }
    ]
});